### PR TITLE
Add support for linking in Engines

### PR DESCRIPTION
**Pull request by trentmwillis**
[Reference for implementation](https://github.com/dgeb/ember-engines/blob/master/addon/-private/link-to-component-ext.js). Was unsure if I should add a test. I can do it, but it will require adding ember-engines to the dependencies and bumping Ember to Canary.

### CODE REVIEW

**Comment by nathanhammond** [comment]
Notes:
- At some point this should drop support for pre-Ember 2.3 because of `getOwner`.
- At some point this won't ship with `_getModels`.

**Comment by nathanhammond** [comment]
Okay @trentmwillis: I bumped everything else and added support for 1.13 (and probably older). I do want to add tests before landing, but this set of changes should make it easier.

Also:
1. We should do this [identically to ember-engines by reopening `FastLinkComponent`](https://github.com/dgeb/ember-engines/blob/master/addon/-private/link-to-component-ext.js) and [adding an initializer](https://github.com/dgeb/ember-engines/blob/master/addon/initializers/engines.js).
2. Can we detect that we're using ember-engines and find some way to snag the `willRender` function off the `reopen`'d `LinkComponent.proto()` to feed into the `FastLinkComponent.reopen`?

**Comment by trentmwillis** [comment]
1. What benefit do we get by reopening the class? Seems like it would make more sense to do it in the actual declaration and avoid any potential race conditions.
2. No way that I know of, other than potentially trying to require a module from that addon (which is obviously bad).

Edit: Also, worth noting that if my [PR for linking between engines](https://github.com/dgeb/ember-engines/pull/75) lands, `LinkComponent` no longer gets re-opened and would invalidate this approach.

**Comment by nathanhammond** [comment]
There won't be race conditions on adding the reopen via `initializer`. That's guaranteed to be run before app boot. Reopening itself isn't actually the goal, though...

I _really_ don't want to get into the business of adding in one-off pieces of code to support every permutation of addons without referencing the code itself from where it's defined. Right now this addon only breaks if there is new API surface area inside of `LinkComponent` since it is all handled by reference to the canonical implementation.

I want to be able to continue in that pattern with addons such that we only break if the addon's API changes, but not if the underlying implementation details change. In pursuit of that I don't mind a runtime check for module existence. "Did you install this addon? Okay, I'll make sure I integrate that into the things that I support."

**Comment by trentmwillis** [comment]
> There won't be race conditions on adding the reopen via initializer.

Not necessarily true. For instance if you wanted to reopen the `FastLinkComponent` in another `initializer` to support tracking events that needed some `willRender` logic, the order in which those reopens occur might matter.

> I really don't want to get into the business of adding in one-off pieces of code to support every permutation of addons without referencing the code itself from where it's defined.

I can understand that concern. I think where I'm coming from is acknowledging that the logic and behavior for Engines is intended to move upstream eventually, so I don't forsee this as being a reliance on another addon forever.

**Comment by nathanhammond** [comment]
I'll land this to master but not publish a release. I don't think this is going to matter with your other PR and https://github.com/nathanhammond/ember-fast-link-to/pull/5/commits/1320e05322153dca790e01330a75c5033f8adcad will simply be reverted out.

**Pull request merged**
